# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and release

on:
  push:
    branches:
    - "master"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [ '11' ]
        maven: [ '3.8.4']
        os: [ 'ubuntu-20.04' ]
    name: Build (Java ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{matrix.java}}
        distribution: 'temurin'
    - name: Restore cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/no/seime
        key: maven

    - name: Build
      run: mvn --batch-mode -DskipChecks package

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          target/*.jar

    - name: Save cache
      if: ${{always()}}
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.m2/repository
        key: maven
